# New ports collection makefile for:	matecommon
# Date created:							12 May 2012
# Whom:									Jin-Sih Lin
#
# $FreeBSD$
#

PORTNAME=	mate-common
PORTVERSION=	1.2.2
CATEGORIES=	devel
MASTER_SITES=	http://pub.mate-desktop.org/releases/1.2/

MAINTAINER=	linpct@gmail.com
COMMENT=	Common automake macros for MATE

USE_BZIP2=	yes
USE_GMAKE=	yes
#USE_GNOME=	pkgconfig
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
